### ISSUE TITLE
Test header images and layout adjustments

### ISSUE THREAD

**Issue by kimisgold** [omeka/theme-santa-fe#6]
There are now header image and accompanying alt text settings available for Santa Fe. Test that the header images appear when uploaded, and look appropriately sized for both desktop and mobile resolutions.

I've also removed Susy, which is a css column layout system that's no longer supported. Look through the theme for any obvious layout oddities, like odd section widths or content sitting where it shouldn't. Exhibit Builder and the item advanced search are areas to look out for.

**Comment by katknow** [comment]
Header and alt text works well across browsers. Header looks appropriately sized in all options through Google's dev tools. 

Did a quick click through and as far as I can tell everything looks fine. Item advanced search definitely looks normal, and a spot check of some exhibits didn't show any issues. Standard browse pages etc. all also seemed good.
